---

- name: Ensuring /var/log/journal is present
  file:
    name: /var/log/journal
    state: directory
  notify: restart journald

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Configuring network
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- name: Ensuring IPVS kernel modules are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh

- name: Ensuring IPVS kernel modules are loaded at boot
  lineinfile:
    state: present
    path: /etc/modules-load.d/ipvs.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh

- name: Enabling systemd-modules-load service
  systemd:
    name: systemd-modules-load
    enabled: yes
    state: started

- name: Adding kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding kubernetes repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-{{ kubernetes_repo_distribution }} main"
    state: present

- name: Making sure kubelet, kubectl, kubeadm, cri-tools are installed
  apt:
    name:
      - openssl
      - kubelet={{ kubelet_version }}-00
      - kubeadm={{ kubeadm_version }}-00
      - kubectl={{ kubectl_version }}-00
      - cri-tools={{ critools_version }}-00
    state: present
    update_cache: yes


- name: Ensuring kubelet extra-args are present on machine
  template:
    src: kubelet_default.j2
    dest: /etc/default/kubelet
  notify: restart kubelet

- name: starting and enabling kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes
