- name: Kubernetes node preparation
  hosts: all
  become: true
  vars:
    kubernetes_repo_distribution: 'xenial'
    kubernetescni_version: '0.7.5'
    docker_version: '18.06.3~ce~3-0~ubuntu'
  roles:
    - ../../roles/kube-node-common

- name: Installing furyagent
  hosts: all
  become: true
  vars:
    furyagent_uri: https://github.com/sighupio/furyagent/releases/latest/download/furyagent-linux-amd64
  roles:
    - ../../roles/furyagent
